CREATE TABLE AUTHORITY (
   ID  BIGINT(50) NOT NULL,
   NAME VARCHAR(255),
   PRIMARY KEY (ID),
   CONSTRAINT AUTHORITY_NAME UNIQUE (NAME)
);


CREATE TABLE USER_ (
   ID  BIGINT(50) NOT NULL,
   ACCOUNT_EXPIRED boolean,
   ACCOUNT_LOCKED boolean,
   CREDENTIALS_EXPIRED boolean,
   ENABLED boolean,
   PASSWORD VARCHAR(255),
   USER_NAME VARCHAR(255),
   PRIMARY KEY (ID),
   CONSTRAINT USER_USER_NAME UNIQUE (USER_NAME)
);


CREATE TABLE USERS_AUTHORITIES (
   USER_ID INT8 NOT NULL,
   AUTHORITY_ID INT8 NOT NULL,
   PRIMARY KEY (USER_ID, AUTHORITY_ID)
   #CONSTRAINT USERS_AUTHORITIES_AUTHORITY FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITY,
   #CONSTRAINT USERS_AUTHORITIES_USER_ FOREIGN KEY (USER_ID) REFERENCES USER_
);

 


