CREATE TABLE COMPANY
(
  ID BIGINT(50) NOT NULL,
  NAME varchar(200) NOT NULL,
  CONSTRAINT COMPANY_PKEY PRIMARY KEY (ID),
  CONSTRAINT UKS7T58YCLDRJRFTPUN092TKHU7 UNIQUE (NAME)
);
#WITH (OIDS=FALSE);