CREATE TABLE CAR
(
  ID BIGINT(50) NOT NULL,
  REGISTRATION_NUMBER varchar(50),
  COMPANY_ID BIGINT(50),
  CONSTRAINT CAR_PKEY PRIMARY KEY (ID),
  CONSTRAINT FKJQP14DKMI2LH5KJAVV4T0DKQY FOREIGN KEY (COMPANY_ID)
      REFERENCES COMPANY (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);
#WITH (OIDS=FALSE);
