CREATE TABLE DEPARTMENT
(
  ID BIGINT(50) NOT NULL,
  NAME varchar(200) NOT NULL,
  COMPANY_ID BIGINT(50),
  CONSTRAINT DEPARTMENT_PKEY PRIMARY KEY (ID),
  CONSTRAINT FKH1M88Q0F7SC0MK76KJU4KCN6F FOREIGN KEY (COMPANY_ID)
      REFERENCES COMPANY (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);
#WITH (OIDS=FALSE);